module.exports = [
  { name: 'Balrog',
    img: 'sf_pics/Balrog.png',
    'Boss': 'true',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'false' },

  { name: 'Chun-li',
    img: 'sf_pics/Chun-Li.png',
    'Boss': 'false',
    'Male': 'false',
    'Female': 'true',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'Dhalsim',
    img: 'sf_pics/Dhalsim.png',
    'Boss': 'false',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'Guile',
    img: 'sf_pics/Guile.png',
    'Boss': 'false',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'false' },

  { name: 'Ken',
    img: 'sf_pics/Ken.png',
    'Boss': 'false',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'M. Bison',
    img: 'sf_pics/M_Bison.png',
    'Boss': 'true',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'Ryu',
    img: 'sf_pics/Ryu.png',
    'Boss': 'false',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'Vega',
    img: 'sf_pics/Vega.png',
    'Boss': 'true',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

  { name: 'Zangief',
    img: 'sf_pics/Zangief.png',
    'Boss': 'false',
    'Male': 'true',
    'Female': 'false',
    'White background': 'false',
    'Swishy lines': 'true' },

    { name: 'Blanka',
      img: 'sf_pics/Blanka.jpg',
      'Boss': 'false',
      'Male': 'true',
      'Female': 'false',
      'White background': 'true',
      'Swishy lines': 'false' },

      { name: 'Honda',
        img: 'sf_pics/Honda.jpg',
        'Boss': 'false',
        'Male': 'true',
        'Female': 'false',
        'White background': 'true',
        'Swishy lines': 'false' },

        { name: 'Sagat',
          img: 'sf_pics/Sagat.jpg',
          'Boss': 'true',
          'Male': 'true',
          'Female': 'false',
          'White background': 'true',
          'Swishy lines': 'false' }
];
